services:
  db:
    image: mysql:8.0
    container_name: godockerDB
    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: courses_platform_proj
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-udocker", "-ppassword"]
      timeout: 20s
      retries: 10
  go:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      db:
        condition: service_healthy
  react:
    image: react-vite
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: always
    depends_on:
      - go